name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: "1.8.3"

      - name: Lint and formatting
        run: biome ci .

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 1.x

      - name: Run tests
        run: deno test
